# -*- coding: utf-8 -*-
"""Week1_capabl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGmZr4Vq_a3tTEomjVzrUBlRcyIFE0MO

##AI Travel Concierge AI Agent Development
"""

!pip install -q groq
!pip install -q groq rich
!pip install rich

"""#Week 1-2: Foundation & Quick Win
Goal: Get something working and deployed early
##
● [ ] Create GitHub repo with proper structure
● [ ] Set up development environment (Python, LangChain, Streamlit)
● [ ] Build basic RAG chatbot with document upload
● [ ] Deploy on Streamlit Cloud
● [ ] Record 2-minute demo video
● [ ] Milestone: Working deployed demo link
"""

from groq import Groq
from rich.console import Console
from rich.panel import Panel

console = Console()
client = Groq(api_key="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")


# 🌍 Attractive welcome UI
welcome = Panel.fit(
"""🌍✈️ 𝐀𝐈 𝐓𝐫𝐚𝐯𝐞𝐥 𝐂𝐨𝐧𝐜𝐢𝐞𝐫𝐠𝐞

Plan trips • Find food • Discover places • Hotels • Budget travel

💬 Tell me what you want:
• Explore a city
• Find food
• Book hotels
• Budget travel
• Luxury experiences

Type 'exit' anytime to stop.
""",
title="✨ Welcome Traveler",
border_style="bright_magenta"
)

console.print(welcome)

# 🧠 Memory system
chat_history = [
    {
        "role": "system",
        "content": """
You are a smart AI Travel Concierge.

Rules:
• Remember conversation context.
• If user already gave budget/location → don't ask again.
• If hotel selected → confirm & give transport tips.
• Ask minimum questions only when needed.
• If food → ask veg/nonveg once only.
• Give short, stylish answers with emojis.
• Talk like human travel assistant.
"""
    }
]

while True:
    user = console.input("\n[bold cyan]You ➤ [/bold cyan]")

    if user.lower() == "exit":
        console.print("\n🌟 Have an amazing journey ahead! ✈️", style="bold magenta")
        break

    chat_history.append({"role": "user", "content": user})

    response = client.chat.completions.create(
        model="meta-llama/llama-4-scout-17b-16e-instruct",
        messages=chat_history,
        temperature=0.7,
        max_tokens=300
    )

    ai_text = response.choices[0].message.content
    chat_history.append({"role": "assistant", "content": ai_text})

    console.print(Panel(ai_text, title="🌟 Travel Concierge", border_style="cyan"))

