# -*- coding: utf-8 -*-
"""WEEK2-AITRAVEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ur3lxzLJ-4y7YQ2XDtKr0LRJJDSCBXN
"""

!pip install -q gradio
!pip install -q langchain==1.0.5 langchain-groq==1.0.0
!pip install -q langchain-community langchain-text-splitters
!pip install -q faiss-cpu pypdf sentence-transformers
!pip install -q duckduckgo-search

from langchain_groq import ChatGroq

GROQ_API_KEY = "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"
llm = ChatGroq(
    model="openai/gpt-oss-20b",
    api_key=GROQ_API_KEY,
    temperature=0.7,
    max_tokens=256
)

from langchain_community.document_loaders import PyPDFLoader

loader1 = PyPDFLoader("/content/Travel_Guide.pdf")
docs1 = loader1.load()

documents = docs1

print("Documents loaded:", len(documents))

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

split_docs = text_splitter.split_documents(documents)

print("Chunks:", len(split_docs))

from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = FAISS.from_documents(split_docs, embeddings)

retriever = vectorstore.as_retriever(search_kwargs={"k":3})

print("Vector database ready")

from duckduckgo_search import DDGS

def web_search(query):
    results = []
    with DDGS() as ddgs:
        for r in ddgs.text(query, max_results=3):
            results.append(r["body"])
    return "\n".join(results)

def rag_search(query):

    docs = retriever.invoke(query)

    context = "\n".join([doc.page_content for doc in docs])

    response = llm.invoke(
        f"""
Answer the question using the travel guide.

Context:
{context}

Question:
{query}
"""
    )

    return response.content

from duckduckgo_search import DDGS

def web_search(query):
    try:
        results = []
        with DDGS() as ddgs:
            for r in ddgs.text(query, max_results=3):
                results.append(r["body"])
        return "\n".join(results)
    except:
        return "No web results found."


def get_response(query):

    try:
        # Retrieve from PDF
        docs = retriever.invoke(query)
        context = "\n".join([doc.page_content for doc in docs])

        # Web search
        web_info = web_search(query)

        # LLM answer
        response = llm.invoke(
        f"""
You are an AI travel assistant.

Use the travel guide if the answer exists there.
If not, use the internet information.

Travel Guide Context:
{context}

Internet Information:
{web_info}

Question:
{query}
"""
        )

        return response.content

    except Exception as e:
        return f"⚠️ Error occurred: {str(e)}"

def get_response(query):

    keywords = ["concert", "event", "news", "today", "schedule"]

    if any(k in query.lower() for k in keywords):

        web_info = web_search(query)

        response = llm.invoke(
            f"""
Answer the question using the internet information.

Internet Info:
{web_info}

Question:
{query}
"""
        )

        return response.content

    else:

        return rag_search(query)

"""Updated WEEK1"""

import gradio as gr

iface = gr.Interface(
    fn=get_response,
    inputs=gr.Textbox(
        label="🌍 Ask the AI Travel Concierge",
        placeholder="Example: What food is famous in Paris? ",
        lines=2
    ),
    outputs=gr.Textbox(label="✈️ Travel Assistant", lines=8),
    title="🌍 AI Travel Concierge",
    description="Answers travel questions using travel guides and internet search.",
    examples=[
        ["Best places to visit in South Korea"],
        ["Are there any tourists places in japan?"]
    ]
)

"""output"""

iface.launch(share=True)

"""WEEK2"""

!pip install streamlit langchain langchain-community langchain-text-splitters faiss-cpu pypdf sentence-transformers langchain-groq

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from langchain_groq import ChatGroq
# from langchain_community.document_loaders import PyPDFLoader
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from langchain_community.vectorstores import FAISS
# 
# st.title("🌍 AI Travel Concierge - RAG Assistant")
# 
# api_key = st.text_input("Enter Groq API Key", type="password")
# 
# uploaded_file = st.file_uploader("Upload Travel Guide PDF", type="pdf")
# 
# if uploaded_file and api_key:
# 
#     with open("temp.pdf","wb") as f:
#         f.write(uploaded_file.read())
# 
#     loader = PyPDFLoader("temp.pdf")
#     docs = loader.load()
# 
#     splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
#     split_docs = splitter.split_documents(docs)
# 
#     embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
# 
#     vectorstore = FAISS.from_documents(split_docs, embeddings)
# 
#     retriever = vectorstore.as_retriever()
# 
#     llm = ChatGroq(
#         model="openai/gpt-oss-20b",
#         api_key=api_key,
#         temperature=0.7
#     )
# 
#     query = st.text_input("Ask a question from the document")
# 
#     if query:
# 
#         docs = retriever.invoke(query)
# 
#         context = "\n".join([d.page_content for d in docs])
# 
#         response = llm.invoke(
#         f"""
#         Use the context below to answer.
# 
#         Context:
#         {context}
# 
#         Question:
#         {query}
#         """
#         )
# 
#         st.subheader("🤖 AI Answer")
#         st.write(response.content)

!zip project.zip app.py requirements.txt

